export const iconRegistry = {
  hidden: require('./hidden.png'),
  view: require('./view.png'),
  mindfireFireLogo: require('./mindfireFireLogo.png'),
  lock: require('./lock.png'),
  people: require('./people.png'),
  back: require('./back.png'),
  email: require('./email.png'),
  googleLight: require('./googleLight.png'),
  googleDark: require('./googleDark.png'),
  faceRecognition: require('./face-recognition.png'),
  fingerprint: require('./fingerprint.png'),
  appleLight: require('./appleLight.png'),
  appleDark: require('./appleDark.png'),
};
